# Rescaling Data

In [38]:
import pandas, scipy, numpy
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer, Binarizer, scale, OneHotEncoder, LabelEncoder
df=pandas.read_csv('QCM Sensor Alcohol Dataset\QCM10.csv',sep=';')
array=df.values

#Separating data into input and output components
x=array[:, 0:14]
y=array[:,0:14]
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(x)
numpy.set_printoptions(precision=3) #setting precision for the output
rescaledX[0:26,:]

array([[1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
        1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [9.966e-01, 9.935e-01, 9.577e-01, 9.590e-01, 9.332e-01, 9.342e-01,
        9.326e-01, 9.319e-01, 9.270e-01, 9.265e-01, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [9.881e-01, 9.856e-01, 9.006e-01, 9.070e-01, 8.666e-01, 8.701e-01,
        8.571e-01, 8.561e-01, 8.514e-01, 8.520e-01, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [9.641e-01, 9.648e-01, 8.494e-01, 8.634e-01, 8.085e-01, 8.157e-01,
        7.915e-01, 7.911e-01, 7.848e-01, 7.871e-01, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [9.255e-01, 9.446e-01, 7.970e-01, 8.255e-01, 7.572e-01, 7.740e-01,
        7.367e-01, 7.423e-01, 7.274e-01, 7.343e-01, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00],
       [7.804e-02, 4.679e-01, 1.515e-01, 3.855e-01, 2.297e-01, 3.866e-01,
        2.909e-01, 3.721e-01, 2

# Standardizing Data

In [39]:
scaler=StandardScaler().fit(x)
rescaledX=scaler.transform(x)
rescaledX[0:26,:]

array([[ 1.953,  1.703,  2.157,  1.967,  2.096,  1.96 ,  1.919,  1.824,
         1.779,  1.715,  2.   , -0.5  , -0.5  , -0.5  ],
       [ 1.944,  1.682,  2.021,  1.827,  1.873,  1.736,  1.705,  1.612,
         1.56 ,  1.495,  2.   , -0.5  , -0.5  , -0.5  ],
       [ 1.919,  1.657,  1.836,  1.649,  1.651,  1.517,  1.465,  1.375,
         1.334,  1.272,  2.   , -0.5  , -0.5  , -0.5  ],
       [ 1.851,  1.59 ,  1.671,  1.5  ,  1.457,  1.331,  1.257,  1.172,
         1.134,  1.078,  2.   , -0.5  , -0.5  , -0.5  ],
       [ 1.742,  1.525,  1.501,  1.371,  1.286,  1.189,  1.083,  1.02 ,
         0.962,  0.92 ,  2.   , -0.5  , -0.5  , -0.5  ],
       [-0.667, -0.012, -0.585, -0.134, -0.473, -0.135, -0.332, -0.135,
        -0.413, -0.267, -0.5  ,  2.   , -0.5  , -0.5  ],
       [-0.738, -0.096, -0.634, -0.208, -0.462, -0.155, -0.25 , -0.084,
        -0.227, -0.119, -0.5  ,  2.   , -0.5  , -0.5  ],
       [-0.763, -0.141, -0.653, -0.246, -0.401, -0.119, -0.166, -0.02 ,
        -0.1  , -0.013, -

# Normalizing Data

In [27]:
scaler=Normalizer().fit(x)
normalizedX=scaler.transform(x)
normalizedX[0:25,:]

array([[-0.104, -0.095, -0.165, -0.149, -0.287, -0.246, -0.422, -0.353,
        -0.54 , -0.439,  0.009,  0.   ,  0.   ,  0.   ],
       [-0.09 , -0.084, -0.166, -0.148, -0.295, -0.25 , -0.422, -0.347,
        -0.544, -0.437,  0.007,  0.   ,  0.   ,  0.   ],
       [-0.081, -0.076, -0.172, -0.15 , -0.3  , -0.249, -0.425, -0.345,
        -0.545, -0.433,  0.006,  0.   ,  0.   ,  0.   ],
       [-0.08 , -0.074, -0.177, -0.151, -0.302, -0.248, -0.426, -0.342,
        -0.545, -0.43 ,  0.006,  0.   ,  0.   ,  0.   ],
       [-0.084, -0.074, -0.184, -0.152, -0.305, -0.246, -0.427, -0.337,
        -0.547, -0.426,  0.005,  0.   ,  0.   ,  0.   ]])

# Binarizing Data

In [40]:
binarizer=Binarizer(threshold=0.1).fit(x)
binaryX=binarizer.transform(x)
binaryX[0:26,:]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0

# Mean Removal

In [41]:
data_standardized=scale(df)
data_standardized.mean(axis=0)

C:\Users\User\anaconda3\envs\matt1998\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


array([-4.663e-17,  7.438e-17, -3.775e-17,  1.976e-16, -1.776e-17,
        1.421e-16,  1.865e-16, -3.908e-16,  1.332e-16, -4.530e-16,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00])

In [ ]:
data_standardized.std(axis=0)

# One Hot Encoding

In [42]:
encoder=OneHotEncoder()
encoder.fit([[0,1,6,2],[1,5,3,5],[2,4,2,7],[1,0,4,2]])

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<type 'numpy.float64'>, handle_unknown='error', n_values=None,
       sparse=True)

In [43]:
encoder.transform([[2,4,3,4]]).toarray()

array([[0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.]])

# Label Encoding

In [44]:
label_encoder=LabelEncoder()
input_classes=['1-Octanol','1-propanol','2-butanol','2-propanol','1-isobutanol']
label_encoder.fit(input_classes)

LabelEncoder()

In [45]:
for i, item in enumerate(label_encoder.classes_):
    print(item,'-->',i)

('1-Octanol', '-->', 0)
('1-isobutanol', '-->', 1)
('1-propanol', '-->', 2)
('2-butanol', '-->', 3)
('2-propanol', '-->', 4)


In [46]:
labels=['1-propanol','2-propanol','1-Octanol']
label_encoder.transform(labels)

array([2, 4, 0], dtype=int64)

In [47]:
label_encoder.inverse_transform(label_encoder.transform(labels))

array(['1-propanol', '2-propanol', '1-Octanol'], dtype='|S12')

# Analyzing Data 

In [48]:
df.describe()

0.799_0.201  0.799_0.201.1  0.700_0.300  0.700_0.300.1  0.600_0.400  \
count    25.000000      25.000000    25.000000      25.000000    25.000000   
mean    -46.595200     -38.462800   -69.836000     -54.778800   -96.049600   
std      18.088082      16.463632    23.992539      19.453662    30.641177   
min     -62.340000     -62.990000   -95.090000     -82.450000  -133.240000   
25%     -60.120000     -42.910000   -84.750000     -60.580000  -114.310000   
50%     -54.470000     -40.010000   -78.190000     -57.700000  -108.080000   
75%     -44.340000     -35.020000   -66.200000     -50.430000   -78.070000   
max     -11.980000     -10.990000   -19.120000     -17.280000   -33.130000   

       0.600_0.400.1  0.501_0.499  0.501_0.499.1  0.400_0.600  0.400_0.600.1  \
count      25.000000    25.000000       25.00000    25.000000      25.000000   
mean      -73.694000  -121.233200      -92.30360  -150.576400    -114.281600   
std        23.554735    38.510871       28.83058    50.543001      37.772045   
min      -107.270000  -168.620000     -128.94000  -210.850000    -161.600000   
25%       -88.440000  -157.680000     -121.95000  -200.980000    -152.810000   
50%       -76.430000  -127.510000      -92.88000  -155.540000    -114.760000   
75%       -59.270000   -89.950000      -68.18000  -102.940000     -80.250000   
max       -28.450000   -48.830000      -40.77000   -62.490000     -50.820000   

       1-Octanol  1-Propanol  2-Butanol  2-propanol  1-isobutanol  
count  25.000000   25.000000  25.000000   25.000000     25.000000  
mean    0.200000    0.200000   0.200000    0.200000      0.200000  
std     0.408248    0.408248   0.408248    0.408248      0.408248  
min     0.000000    0.000000   0.000000    0.000000      0.000000  
25%     0.000000    0.000000   0.000000    0.000000      0.000000  
50%     0.000000    0.000000   0.000000    0.000000      0.000000  
75%     0.000000    0.000000   0.000000    0.000000      0.000000  
max     1.000000    1.000000   1.000000    1.000000      1.000000

In [49]:
df.shape

(25, 15)

In [50]:
df.head(10)

0.799_0.201  0.799_0.201.1  0.700_0.300  0.700_0.300.1  0.600_0.400  \
0       -11.98         -10.99       -19.12         -17.28       -33.13   
1       -12.15         -11.33       -22.33         -19.95       -39.82   
2       -12.58         -11.74       -26.67         -23.34       -46.48   
3       -13.79         -12.82       -30.56         -26.18       -52.30   
4       -15.73         -13.87       -34.54         -28.65       -57.44   
5       -58.41         -38.66       -83.58         -57.33      -110.24   
6       -59.68         -40.01       -84.75         -58.75      -109.91   
7       -60.12         -40.73       -85.19         -59.47      -108.08   
8       -60.41         -41.20       -84.73         -59.31      -106.46   
9       -60.87         -39.88       -84.22         -57.58      -105.32   

   0.600_0.400.1  0.501_0.499  0.501_0.499.1  0.400_0.600  0.400_0.600.1  \
0         -28.45       -48.83         -40.77       -62.49         -50.82   
1         -33.64       -56.90         -46.77       -73.32         -58.96   
2         -38.69       -65.95         -53.46       -84.53         -67.21   
3         -42.98       -73.81         -59.19       -94.41         -74.40   
4         -46.26       -80.37         -63.49      -102.94         -80.25   
5         -76.80      -133.77         -96.13      -171.05        -124.15   
6         -77.28      -130.65         -94.69      -161.81        -118.70   
7         -76.43      -127.51         -92.88      -155.54        -114.76   
8         -75.39      -124.62         -90.88      -151.56        -112.58   
9         -73.36      -122.59         -88.28      -146.99        -109.52   

   1-Octanol  1-Propanol  2-Butanol  2-propanol  1-isobutanol  
0          1           0          0           0             0  
1          1           0          0           0             0  
2          1           0          0           0             0  
3          1           0          0           0             0  
4          1           0          0           0             0  
5          0           1          0           0             0  
6          0           1          0           0             0  
7          0           1          0           0             0  
8          0           1          0           0             0  
9          0           1          0           0             0

In [51]:
df.groupby('1-Octanol').size()

1-Octanol
0    20
1     5
dtype: int64

In [52]:
df.rename(columns = {'0.799_0.201':'concentration1','0.799_0.201.1':'concentration1_2','0.700_0.300':'concentration2','0.700_0.300.1':'concentration2_2','0.600_0.400':'concentration3','0.600_0.400.1':'concentration3_2',
                    '0.501_0.499':'concentration4','0.501_0.499.1':'concentration4_2','0.400_0.600':'concentration5','0.400_0.600.1':'concentration5_2','1-Octanol':'1-Octanol',
                    '1-Propanol':'1-Propanol','2-Butanol':'2-Butanol','2-propanol':'2-propanol','1-isobutanol':'1-isobutanol'},inplace=True)

In [53]:
print(df.head(10))

   concentration1  concentration1_2  concentration2  concentration2_2  \
0          -11.98            -10.99          -19.12            -17.28   
1          -12.15            -11.33          -22.33            -19.95   
2          -12.58            -11.74          -26.67            -23.34   
3          -13.79            -12.82          -30.56            -26.18   
4          -15.73            -13.87          -34.54            -28.65   
5          -58.41            -38.66          -83.58            -57.33   
6          -59.68            -40.01          -84.75            -58.75   
7          -60.12            -40.73          -85.19            -59.47   
8          -60.41            -41.20          -84.73            -59.31   
9          -60.87            -39.88          -84.22            -57.58   

   concentration3  concentration3_2  concentration4  concentration4_2  \
0          -33.13            -28.45          -48.83            -40.77   
1          -39.82            -33.64          -56.9

In [54]:
output = pandas.DataFrame(df, columns = ['concentration1','concentration1_2','concentration2','concentration2_2','concentration3','concentration3_2','concentration4','concentration4_2','concentration5','concentration5_2','1-Octanol','1-Propanol'
                                        ,'2-Butanol','2-propanol','1-isobutanol'])
output.to_csv (r'C:\Users\User\Documents\UiTM\FSKM\CS259\Sem 4 Sub\ISP 560\ISP 560 Project\QCM10(cleaned).csv', index=False, header=True)

In [ ]:
output2 = pandas.DataFrame(df, columns = ['concentration1','concentration1_2','concentration2','concentration2_2','concentration3','concentration3_2','concentration4','concentration4_2','concentration5','concentration5_2','1-Octanol','1-Propanol'
                                        ,'2-Butanol','2-propanol','1-isobutanol'])
output2.to_csv (r'C:\Users\User\Documents\UiTM\FSKM\CS259\Sem 4 Sub\ISP 560\ISP 560 Project\QCM10(cleaned)(without header).csv', index=False, header=False)